CREATE TABLE candidatures (
                              id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                              entreprise VARCHAR(255) NOT NULL,
                              poste VARCHAR(255) NOT NULL,
                              statut VARCHAR(50) NOT NULL,
                              date_candidature DATE NOT NULL,
                              lien_annonce VARCHAR(255),
                              notes TEXT,
                              user_id BIGINT NOT NULL REFERENCES users(id)
);